services:
  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_DATABASE: postgres
      DB_USERNAME: postgres
    command: ["make", "test-coverage", "analyse", "lint"]

  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
