name: CI status

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Кэш Docker слоёв
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: docker-${{ github.sha }}
          restore-keys: |
            docker-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run CI
        run: |
          make ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: build/logs/clover.xml
