name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run CI
        run: |
          make ci
